### ISSUE TITLE
Flutter 升级到 1.17 以后 IOS版本地图上无法添加覆盖物

### ISSUE THREAD

**Issue by wxbhlj** [fluttify-project/amap_all_fluttify#12]
return Stack(

      children: <Widget>[
        _amap(),
        _buildAddressBar(),
      ],
    );

地图可以显示，AddressBar 就显示不了。Android 上面正常。IOS上面有问题。
PS：未升级到Flutter 1.17 之前两个版本都正常

**Comment by yohom** [comment]
试一下0.22.2以上的版本

**Comment by wxbhlj** [comment]
神奇，升级后好了。😄👍
