### ISSUE TITLE
打包出错

### ISSUE THREAD

**Issue by Spicely** [fluttify-project/amap_all_fluttify#4]
![image](https://user-images.githubusercontent.com/10075622/75219483-da48a300-57d7-11ea-951d-f3fe19afd47e.png)
我的包
 cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0
  cookie_jar: ^1.0.1
  dio: ^3.0.8
  dio_cookie_manager: ^1.0.0
  toast: ^0.1.5
  json_annotation: ^3.0.1
  streaming_shared_preferences: ^1.0.1
  provider: ^4.0.4
  date_format: ^1.0.8
  image_picker: ^0.6.3+1
  flushbar: ^1.9.1
  amap_all_fluttify: ^0.11.1
  permission_handler: ^4.2.0+hotfix.3
  install_plugin: ^2.0.1
  package_info: ^0.4.0+13
  flutter_html: ^0.11.1
  vibrate: ^0.0.4
  audioplayers: ^0.14.0
  web_socket_channel: ^1.1.0

修改grade版本后
![image](https://user-images.githubusercontent.com/10075622/75219566-17149a00-57d8-11ea-9797-614fe30e5191.png)

**Comment by lghItem** [comment]
我也遇到跟你一样的问题,我把permission_handler删掉就可以编译成功; 现在还没找到解决方法,兄弟你找到了没?

**Comment by Spicely** [comment]
> 我也遇到跟你一样的问题,我把permission_handler删掉就可以编译成功; 现在还没找到解决方法,兄弟你找到了没?
我换成3个单独的包使用了 部分包考虑降级
vibrate 包和这个包冲突
