### ISSUE TITLE
AmapSearch.searchAround   iOS无法调用成功

### ISSUE THREAD

**Issue by ningyibo** [fluttify-project/amap_all_fluttify#9]

**Comment by ningyibo** [comment]
android可正常显示

**Comment by yohom** [comment]
上一下报错信息

**Comment by tulipwang123** [comment]
在根目录的pubspec.yaml里添加依赖后报以下错误，请教如何解决？先感谢
Couldn't read file LocalFile: 'D:\flutter_demo\hybrid-development-demo\android\src\main\kotlin\me\yohom\amap_all_fluttify\AmapAllFluttifyPlugin.kt' even though it exists. Please verify that this file has read permission and try    
again.

pubspec.yaml配置如下
name: flutter_myDemo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_search_fluttify: ^0.8.2+1
  amap_location_fluttify: ^0.10.0+e74b91b
  amap_map_fluttify: ^0.19.1+b2681d9
  amap_all_fluttify: ^0.13.1+1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
      androidPackage: me.yohom.amap_all_fluttify
      pluginClass: AmapAllFluttifyPlugin

  uses-material-design: true
  assets:
    - assets/images/

**Comment by kimmy-wang** [comment]
ios
```
flutter: fluttify-dart: AMapSearchAPI@10757181568::AMapDrivingRouteSearch([])
flutter: fluttify-dart-callback: AMapSearchRequest_didFailWithError([])
flutter: AMapSearchRequest_didFailWithError::kNativeObjectPool: {AMapServices{refId: 10758148800}, AMapSearchAPI{refId: 10757181568}, AMapGeoPoint{refId: 10767851552}, AMapGeoPoint{refId: 10767889024}, AMapDrivingRouteSearchRequest{refId: 10791332992}, NSObject{refId: 10791332992}, NSError{refId: 8395939087007980572}}
flutter: Exception: Error Domain=AMapSearchErrorDomain Code=1008 "INVALID_USER_SCODE" UserInfo={NSLocalizedDescription=INVALID_USER_SCODE}
```
